require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Binder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_native_modules!
  # Pods for Binder
  

end
